config/routes.rb
Reddit::Application.routes.draw do
  get "profiles/show"
  get "comments/new"
  get "comments/create"
  devise_for :users
  resources :submissions do
    get 'upvote'
    get 'downvote'

    resources :comments
  end
  root 'submissions#index'
  get ':username' => 'profiles#show', :as => :profile

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope order('created_at DESC')
  
  belongs_to :user
  belongs_to :submission

  validates :user, presence: true
  validates :submission, presence: true
  validates :text, presence: true, length: {minimum: 5}
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  default_scope order('created_at DESC')

  belongs_to :user
  has_many :comments
  
  validates :link, format: URI::regexp(%w(http https)), presence: true
  validates :title, presence: true
  validates :user, presence: true

  # if we want links to be unique
  # validates :link, uniqueness: true

  # if we want to constrain the length
  # validates :title, length: {in: 6..10}

  def upvote
    self.votes += 1
    self.save
  end

  def downvote
    self.votes -= 1
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :submissions
  has_many :comments
  
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  def new
    @submission = Submission.find(params[:submission_id])
    @comment = @submission.comments.new
  end

  def create
    @submission = Submission.find(params[:submission_id])
    @comment = @submission.comments.new(params[:comment].permit(:text).merge(user: current_user))
    if @comment.save
      redirect_to @submission
    else
      render 'new'
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_username(params[:username])
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:upvote, :downvote, :new, :create, :edit, :destroy]
  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all.order('votes DESC')
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = current_user.submissions.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @submission }
      else
        format.html { render action: 'new' }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end

  def upvote
    @submission = Submission.find(params[:submission_id])
    @submission.upvote
    redirect_to :back
  end

  def downvote
    @submission = Submission.find(params[:submission_id])
    @submission.downvote
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:link, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= simple_form_for([@submission, @comment]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">
        <header id="global-header">
          <a href="/" id="reddit-header" title="">reddit.com</a>
            <ul id="nav-links">
              <% if current_user %>
                <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
            </ul>
        </header>
      </div>
      
    </div>
    <div class="row">
      <div class="large-12 columns">
        <% if flash[:error] %>
          <%= content_tag :div, :id => "flash_name", :class => "alert-box error" do %>
            <%= flash[:error] %>
            <a class="close">x</a>
          <% end %>
        <% end %>

        <% if flash[:notice] %>
          <%= content_tag :div, :id => "flash_name", :class => "alert-box success" do %>
            <%= flash[:notice] %>
            <a class="close">x</a>
          <% end %>
        <% end %>
      </div><!-- //.twelve.columns -->
    </div><!-- //.row -->
    <div class="row" id="container">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
    

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/profiles/show.html.erb
<h1>Submissions by <%= @user.username %></h1>

<% @user.submissions.each do |submission| %>
  <div class="submission_index row">
    <div class="vote_count large-1 columns">
      <%= link_to "", submission_upvote_path(submission), class: "upvote-arrow" %>
      <span class="vote-count"><%= submission.votes %></span>
      <%= link_to "", submission_downvote_path(submission), class: "downvote-arrow" %>
    </div>
    <div class="large-11 columns">
      <%= link_to submission.title, submission.link, class: 'submission_link' %>
    </div>
    <div class="large-11 columns">
      <span class="subtitle">
        submitted by <%= link_to submission.user.username, profile_path(submission.user.username) %> <%= time_ago_in_words submission.created_at %> ago
        <%= link_to submission.comments.count.to_s + " comments", submission %>
      </span>
      
    </div>
    
  </div>
  
<% end %>


<h1>Comments by <%= @user.username %></h1>

<div class="comments row">
  <% if !@user.comments.blank? %>
    <% for comment in @user.comments %>
      <div class="large-12 columns comment">
        <div class="large-12 columns comment-meta">
          <span class="user"><%= link_to comment.user.username, profile_path(comment.user.username) %></span> <%= time_ago_in_words comment.created_at %> ago on <%= link_to comment.submission.title, submission_path(comment.submission) %>
        </div>
        <div class="large-12 columns comment-body">
          <%= comment.text %>    
        </div>
      </div>
      
    <% end %>
  <% else %>
    
  <% end %>
</div>

app/views/submissions/_form.html.erb
<%= simple_form_for(@submission) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :link %>
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<% @submissions.each do |submission| %>
  <div class="submission_index row">
    <div class="vote_count large-1 columns">
      <%= link_to "", submission_upvote_path(submission), class: "upvote-arrow" %>
      <span class="vote-count"><%= submission.votes %></span>
      <%= link_to "", submission_downvote_path(submission), class: "downvote-arrow" %>
    </div>
    <div class="large-11 columns">
      <%= link_to submission.title, submission.link, class: 'submission_link' %>
    </div>
    <div class="large-11 columns">
      <span class="subtitle">
        submitted by <%= link_to submission.user.username, profile_path(submission.user.username) %> <%= time_ago_in_words submission.created_at %> ago
        <%= link_to submission.comments.count.to_s + " comments", submission %>
      </span>
      
    </div>
    
  </div>
  
<% end %>

<%= link_to 'New Submission', new_submission_path, class: 'button' %>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render 'form' %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<div class="submission_index row">
  <div class="vote_count large-1 columns">
      <%= link_to "", submission_upvote_path(@submission), class: "upvote-arrow" %>
      <span class="vote-count"><%= @submission.votes %></span>
      <%= link_to "", submission_downvote_path(@submission), class: "downvote-arrow" %>
  </div>
  <div class="large-11 columns">
    <%= link_to @submission.title, @submission.link, class: 'submission_link' %>
  </div>
  <div class="large-11 columns">
    <span class="subtitle">
      submitted by <%= link_to @submission.user.username, profile_path(@submission.user.username) %> <%= time_ago_in_words @submission.created_at %> ago
      <%= link_to @submission.comments.count.to_s + " comments", @submission %>
    </span>
    
  </div>
  
</div>


<div class="comments row">
  <% if !@submission.comments.blank? %>
    <% for comment in @submission.comments %>
      <div class="large-12 columns comment">
        <div class="large-12 columns comment-meta">
          <span class="user"><%= link_to comment.user.username, profile_path(comment.user.username) %></span> <%= time_ago_in_words comment.created_at %> ago
        </div>
        <div class="large-12 columns comment-body">
          <%= comment.text %>    
        </div>
      </div>
      
    <% end %>
  <% else %>
    
  <% end %>
</div>

<%= link_to "New Comment", new_submission_comment_path(@submission), class: "button" %>